#!/usr/bin/env bash
# this script fetches the subdomain information and the record type

domain=$1
subdomain=$2

print_subdomain_info() {
	# get the dig results
	out=$(dig +noall +answer "$1.$2")

	# parse the record and the ip address from the dig results
	record=$(echo "$out" | head -1 | awk '{print $4}')
	address=$(echo "$out" | tail -1 | awk '{print $5}')

	# print results
	echo "The subdomain $subdomain is a $record record \
and points to $address"
}

if [ -z "$domain" ];
then
	echo "Usage: $0 <domain> [<subdomain>]"
	exit 1
fi

if [ -z "$subdomain" ];
then
	for subdomain in www lb_01 web_01 web_02; do
		print_subdomain_info "$subdomain" "$domain"
	done
else
	print_subdomain_info "$subdomain" "$domain"
fi
