#!/usr/bin/env bash
# This script installs nginx on Ubuntu server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
