#!/usr/bin/env bash
# Configure HAProxy load balancer on Ubuntu Server

# update system and install deps
sudo apt-get -y update
sudo apt-get -y install software-properties-common

# install HAProxy and its repo
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

# enable HAProxy to start on system boot
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy

# configure HAProxy
config="
frontend davenchy_frontend
	bind *:80
	default_backend davenchy_backend

backend davenchy_backend
	balance roundrobin
	server 286473-web_01 54.165.85.96:80 check
	server 286473-web_02 54.175.189.248:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg

# apply changes
if [[ "$(pgrep -f haproxy)" ]]; then
	sudo service haproxy restart
else
	sudo service haproxy start
fi
