#!/usr/bin/env bash
# For real I don't understand why Sylvain created such a task, it's humiliation
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx stop
sudo killall5 -9 nginx  # sometimes ALX tasks is challenging
