#!/usr/bin/env bash
# This scripts prints a stroy for each user in passwd
while read -r line; do
  IFS=: read -ra array <<< "$line"
	echo "The user ${array[0]} is part of the ${array[3]} gang, \
lives in ${array[5]} and rides ${array[6]}. \
${array[2]}'s place is protected by the passcode ${array[1]}, \
more info about the user here: ${array[4]}"
done < /etc/passwd
