#!/usr/bin/env bash
# Displays bad,good luck on 4th and 8th lines otherwise Best School, total 10l
i=0
while [ $i -lt 10 ]; do
	if [ $i -eq 3 ]; then echo "bad luck"
	elif [ $i -eq 7 ]; then echo "good luck"
	else echo "Best School"
	fi
	i=$((i+1))
done
