#!/usr/bin/env bash
# from 1-20, bad luck from china,japan,italy for 4,9,17
i=0
while [ $i -le 779 ]; do
	h=$((i%60))
	if [ $h -eq 0 ]
	then
		echo "Hour: $((i/60))"
	else
		echo $h
	fi
	i=$((i+1))
done
