#!/usr/bin/env bash
# This script gives information about a file called school

file="school"

# check if file is exists
if [ -e $file ]
then
	echo "$file file exists"
	# check if file is empty
	if [ -s $file ]
	then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi

	# check if file is a regular file
	if [ -f $file ]
	then
		echo "$file is a regular file"
	fi
else
	echo "$file file does not exist"
fi
