#!/usr/bin/env bash
# This script well change the ip addresses for localhost and facebook.com

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
mv -f ~/hosts.new /etc/hosts
