#!/usr/bin/env bash
# This script changes the ip addresses for localhost and facebook.com

hosts="/hosts.new"
cp /etc/hosts $hosts
sed -i 's/^.*127\.0\.0\.1.*$//' $hosts
echo "127.0.0.2 localhost" >> $hosts
echo "8.8.8.8 facebook.com" >> $hosts
cp -f $hosts /etc/hosts
